### PR TITLE
Elixir 1.10.4 otp23.1 npm 6

### PR DESCRIPTION
**Pull request by yannvery**
Use elixir 1.10.4
Use npm 6.11.4 instead of npm 5, which comes with nodejs 9.7

### CODE REVIEW

**Review by happypoulp — APPROVED** [review]
👍  LGTM

**Comment by csaunier** [comment]
I've seen we are using node@9.7

We should use an even version as odd have very low duration life and no support.

See here : https://nodejs.org/en/about/releases/

This may be out of this PR scope, but we should upgrade to at least 10.23.1

**Review by csaunier — APPROVED** [review]

**Comment by yannvery** [comment]
> I've seen we are using node@9.7
> 
> We should use an even version as odd have very low duration life and no support.
> 
> See here : https://nodejs.org/en/about/releases/
> 
> This may be out of this PR scope, but we should upgrade to at least 10.23.1

I agree @csaunier, does it a good idea to use the last LTS, which is 14.15.4 ?
I've already a valid image and a version of Connect that works correctly with this version.

**Comment by csaunier** [comment]
> > I've seen we are using node@9.7
> > We should use an even version as odd have very low duration life and no support.
> > See here : https://nodejs.org/en/about/releases/
> > This may be out of this PR scope, but we should upgrade to at least 10.23.1
> 
> I agree @csaunier, does it a good idea to use the last LTS, which is 14.15.4 ?
> I've already a valid image and a version of Connect that works correctly with this version.

On front side, we are only using 10.23.1 on our projects.

I think it's good to update all of our scope to the last LST (v14), but to be coherent, perhaps we should stay everywhere on v10, and make another task to update all.

What do you think @Zeboch @happypoulp ?

**Comment by happypoulp** [comment]
> > > I've seen we are using node@9.7
> > > We should use an even version as odd have very low duration life and no support.
> > > See here : https://nodejs.org/en/about/releases/
> > > This may be out of this PR scope, but we should upgrade to at least 10.23.1
> > 
> > 
> > I agree @csaunier, does it a good idea to use the last LTS, which is 14.15.4 ?
> > I've already a valid image and a version of Connect that works correctly with this version.
> 
> @yannvery
> 
> On front side, we are only using 10.23.1 on our projects.
> 
> I think it's good to update all of our scope to the last LST (v14), but to be coherent, perhaps we should stay everywhere on v10, and make another task to update all.
> 
> What do you think @Zeboch @happypoulp ?

I agree that having the same version everywhere is the safest approach (and I do like consistency).

But since that consistency will not be enforced programatically (we have different docker images), there is nothing that prevents us from trying out the LTS version.

However I agree that it's best to choose either the LTS or the same as we use on other frontend projects.

**Comment by Zeboch** [comment]
@csaunier, @happypoulp, @yannvery  since elixir image is only used for elixir project and the npm package itselves are only used inside this perimeter (outside frontend perimeter), I suggest to use the last LTS (14.15.4) or at least the jobteaser/ui-jobteaser version.

**Comment by yannvery** [comment]
Here we go with Node `14.15.4`.

**Pull request merged**
