### PR TITLE
[SEC-105] Update Ruby to 2.5.3 because of an OpenSSL CVE

### PR DESCRIPTION
**Pull request by vlatkapavisic**

### CODE REVIEW

**Comment by gearnode** [comment]
@lukkor I agree your point 😄

**Comment by vlatkapavisic** [comment]
@lukkor all the tests pass in the JT PR https://github.com/jobteaser/jobteaser/pull/11507 except one random test that Florent will fix. Should I merge this PR?

**Comment by gearnode** [comment]
@vlatkapavisic While we have issue with our CI you can't merge the image update.

**Comment by lukkor** [comment]
IMO, this PR can be merged but not the jobteaser one. The problem is clearly on jobteaser side and jobteaser will not use the new version of ruby until the image tag is created and #11507 is merged.

**Pull request merged**
